# Site + Plant Parameters
site:
  depth: 22.5
  distance: 124
  distance_to_landfall: 35
  mean_windspeed: 9
plant:
  layout: grid
  num_turbines: 50
  row_spacing: 7
  substation_distance: 1
  turbine_spacing: 7
landfall:
  interconnection_distance: 3
  trench_length: 2
turbine: 12MW_generic
# Vessels
array_cable_install_vessel: example_cable_lay_vessel
export_cable_install_vessel: example_cable_lay_vessel
export_cable_bury_vessel: example_cable_lay_vessel
oss_install_vessel: example_heavy_lift_vessel
spi_vessel: example_scour_protection_vessel
wtiv: example_wtiv
# Module Specific
OffshoreSubstationInstallation:
  feeder: example_heavy_feeder
  num_feeders: 1
array_system_design:
  cables:
  - XLPE_630mm_33kV
  - XLPE_400mm_33kV
export_system_design:
  cables: XLPE_500mm_132kV
  percent_added_length: 0.0
scour_protection_design:
  cost_per_tonne: 40
  scour_protection_depth: 1
# Configured Phases
design_phases:
- MonopileDesign
- ScourProtectionDesign
- ArraySystemDesign
- ExportSystemDesign
- OffshoreSubstationDesign
install_phases:
  ArrayCableInstallation: 0
  ExportCableInstallation: 2000
  MonopileInstallation: 0
  OffshoreSubstationInstallation: 0
  ScourProtectionInstallation: 0
  TurbineInstallation: 0
# Project Inputs
project_parameters:
  turbine_capex: 1500
